name: CI

# on:
  # push:
    # branches: [ master ]
  # pull_request:
    # branches: [ master ]
on:
  push:
    branches:
      - '*'

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        php:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
        symfony:
          - '4.4.*'
          - '5.0.*'
          - '5.1.*'
          - '5.2.*'
          - '5.3.*'
          - '5.4.*'
          - '6.0.*'
        exclude:
          - php: '7.1'
            symfony: '5.0.*' # requires PHP ^7.2.5
          - php: '7.1'
            symfony: '5.1.*' # requires PHP ^7.2.5
          - php: '7.1'
            symfony: '5.2.*' # requires PHP ^7.2.5
          - php: '7.1'
            symfony: '5.3.*' # requires PHP ^7.2.5
          - php: '7.1'
            symfony: '5.4.*' # requires PHP ^7.2.5
          - php: '7.1'
            symfony: '6.0.*' # requires PHP ^8.0.2
          - php: '7.2'
            symfony: '6.0.*' # requires PHP ^8.0.2
          - php: '7.3'
            symfony: '6.0.*' # requires PHP ^8.0.2
          - php: '7.4'
            symfony: '6.0.*' # requires PHP ^8.0.2

    runs-on: ${{ matrix.os }}
    env:
      SYMFONY: ${{ matrix.symfony }}

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: date.timezone='UTC'
          tools: composer:v2

      - name: Require symfony
        run: composer --no-update require symfony/symfony:"${SYMFONY}"

      - name: Install dependencies
        run: |
          composer update
          vendor/bin/simple-phpunit install

      - name: Test
        run: |
          composer validate --strict --no-check-lock
          vendor/bin/simple-phpunit --coverage-text --verbose
